PFN classifier
automl/PFNs pull request #1
Opened 2023-11-20 21:32 UTC by omarswelam

Adding PFNClassifier with multivalued classification functionality using a TransformerModel checkpoint under models_diff. Additionally, openml dataset generation scripts were added for testing. Implementations of added scripts follow the implementation procedures for the TabPFN classification class.

2024-01-09 10:37 UTC, SamuelGabriel requested changes
Thanks a lot! This will make a lot of people happy. My main points are just naming. The names in the tabpfn repository are assuming everyone wants to work on TabPFN, but here they should not assume that. That is why I propose to rename a few files.

Could you please add a section to the readme describing how to load and evaluate the TabPFN in this repo.

I did not review most of the code, as it is mostly copied (which it should be of course).
Could you point me to the positions where you had to make the most manual changes and could not just copy paste from TabPFN?

Generally, this looks fine though, let me just make one last pass after renaming and with a bit more info on which parts you had to put work in.

2024-01-09 10:37 UTC, SamuelGabriel commented on pfns/scripts/model_builder.py
please rename this to `tabpfn_model_builder.py`

2024-01-09 10:37 UTC, SamuelGabriel commented on pfns/datasets/__init__.py
Please move this into a subfolder `pfns/datasets/tabular_datasets`.

2024-01-09 10:37 UTC, SamuelGabriel commented on pfns/scripts/transformer_prediction_interface.py
rename this to `tabpfn_interface.py`

2024-01-18 11:36 UTC, omarswelam commented on pfns/scripts/model_builder.py
My main manual modifications from the TabPFN code were mainly in 2 parts here:

1) The arguments passed to the `TransformerModel` during initialization. In PFNs, the `n_out` is defined in the `decoder_dict={'standard': (None, n_out)}`, unlike in TabPFN.

2) Renaming for the decoder layers, due to the difference in the naming of the decoder layers while building from the `decoder_dict`.

2024-01-18 11:49 UTC, omarswelam commented on pfns/scripts/transformer_prediction_interface.py
Main modifications to the TabPFN:

1) Removing the CustomUnpickler functionalities since it wasn't needed for loading the pre-trained model being used.
2) Removing the `load_model` function and the condition in the model loading pipeline, since only the `load_model_only_inference` is implemented, in the part shown below:
```python
    if only_inference:
        # print('Loading model that can be used for inference only')
        model, c = load_model_only_inference(base_path, model_file, device)
    else:
        #until now also only capable of inference
        model, c = load_model(base_path, model_file, device, eval_positions=[], verbose=False)
    #model, c = load_model(base_path, model_file, device, eval_positions=[], verbose=False)
```

2024-01-18 12:02 UTC, omarswelam commented on pfns/scripts/model_builder.py
> +                             dropout=config_sample['dropout'], decoder_dict={'standard': (None, n_out)},
change related to the `n_out` argument.

2024-01-18 12:02 UTC, omarswelam commented on pfns/scripts/model_builder.py
> +    for key in list(model_state.keys()):
renaming of decoder layers.

2024-02-01 16:38 UTC, SamuelGabriel commented on pfns/scripts/model_builder.py
Thanks!

2024-02-01 16:38 UTC, SamuelGabriel commented on pfns/scripts/transformer_prediction_interface.py
yeah great

2024-02-01 16:40 UTC, SamuelGabriel commented
this looks great, thank you. i am merging this now :)

2024-02-01 16:40 UTC, merged